name: run app.py

on:
  push:
  schedule:
    - cron: '0 */3 * * *' # Every 3 Hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ROOM_ID: ${{ secrets.ROOM_ID }}
        run: python app.py
          

      - name: commit files
        run: |
          git config --global user.email "sathanalao@hotmail.com"
          git config --global user.name "mark48853"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "🤖:updated" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
